//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADBN.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hulls
    {
        public int Id { get; set; }
        public string Manafacture { get; set; }
        public string hullType { get; set; }
        public string hullModel { get; set; }
        public string cost { get; set; }
    }
}
