//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADBN.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotherBord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotherBord()
        {
            this.NoteBook = new HashSet<NoteBook>();
            this.PC = new HashSet<PC>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string northBridge { get; set; }
        public string chipSet { get; set; }
        public int SoketId { get; set; }
        public Nullable<int> Allowable_generationID { get; set; }
        public Nullable<int> RAM_MarkingAllowable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteBook> NoteBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
        public virtual Soket Soket { get; set; }
        public virtual MarkerTable MarkerTable { get; set; }
        public virtual MemoryGeneration MemoryGeneration { get; set; }
    }
}
