//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADBN.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        public int Id { get; set; }
        public string Marking { get; set; }
        public Nullable<int> processor_ID { get; set; }
        public Nullable<int> motherBord_ID { get; set; }
        public Nullable<int> RAM_ID { get; set; }
        public Nullable<int> videoCard_ID { get; set; }
        public Nullable<int> disc1_ID { get; set; }
        public Nullable<int> disc2_ID { get; set; }
        public Nullable<int> disc3_ID { get; set; }
        public Nullable<int> disc4_ID { get; set; }
        public Nullable<int> hull_ID { get; set; }
        public Nullable<int> power_Supply_ID { get; set; }
        public Nullable<int> existence { get; set; }
        public Nullable<int> reservet { get; set; }
        public Nullable<int> cost { get; set; }
        public string Note { get; set; }
    
        public virtual Disc Disc { get; set; }
        public virtual Disc Disc1 { get; set; }
        public virtual Disc Disc2 { get; set; }
        public virtual Disc Disc3 { get; set; }
        public virtual MotherBord MotherBord { get; set; }
        public virtual PowerSourse PowerSourse { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual VideoBord VideoBord { get; set; }
    }
}
