//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADBN.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processor()
        {
            this.NoteBook = new HashSet<NoteBook>();
            this.PC = new HashSet<PC>();
        }
    
        public int Id { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public Nullable<int> frequency { get; set; }
        public Nullable<int> cache { get; set; }
        public Nullable<int> number_of_Cores { get; set; }
        public Nullable<int> number_of_threads { get; set; }
        public Nullable<int> cost { get; set; }
        public int SoketId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteBook> NoteBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
        public virtual Soket Soket { get; set; }
    }
}
