//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADBN.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PositionsEntities : DbContext
    {
        public PositionsEntities()
            : base("name=PositionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disc> Disc { get; set; }
        public virtual DbSet<Hulls> Hulls { get; set; }
        public virtual DbSet<MotherBord> MotherBord { get; set; }
        public virtual DbSet<NoteBook> NoteBook { get; set; }
        public virtual DbSet<PC> PC { get; set; }
        public virtual DbSet<PowerSourse> PowerSourse { get; set; }
        public virtual DbSet<Processor> Processor { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<VideoBord> VideoBord { get; set; }
        public virtual DbSet<Soket> SoketSet { get; set; }
        public virtual DbSet<MarkerTable> MarkerTable { get; set; }
        public virtual DbSet<MemoryGeneration> MemoryGeneration { get; set; }
    }
}
